### PR TITLE
Added inventory server when using cloud-scanner-api

### PR DESCRIPTION
**Pull request by notCamelCaseName**
Added a rocket server that listens on `/inventory` and provides an aws inventory as json using already existing code.

⚠️ Warning : couldn't test it as I don't have credentials for an aws instance

### CODE REVIEW

**Comment by notCamelCaseName** [comment]
I also fixed a typo in aws_inventory.rs

**Comment by demeringo** [comment]
@notCamelCaseName thank you for the PR.

Could you please integrate the latest changes from dev branch to this PR (mostly dependencies updates) ?

**Comment by notCamelCaseName** [comment]
Should be good now, i chose to integrate stats on execution time directly into the `get_inventory_as_json` function (used by the server)

**Comment by demeringo** [comment]
Thank you, I tested with an aws account and it looks good.

I intend to work on #285 (which would also mean #310) today, so I may introduce some changes on the format of the json output.

**Pull request merged**
